spring.application.name=session7
#DB
spring.datasource.url=jdbc:postgresql://localhost:5432/recruit
spring.datasource.username=postgres
spring.datasource.password=123456
#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh
